### ISSUE TITLE
Is accessing my data for all websites really necessary?

### ISSUE THREAD

**Issue by Macxim** [daiyitastic/random-wikipedia-newtab-extension#1]
Hi, 
Cool extension, thanks for your work.
One question though: Is accessing my data for all websites really necessary?

![screen shot 2018-04-01 at 00 43 56](https://user-images.githubusercontent.com/1909957/38168505-e595f0c0-3545-11e8-9eb2-5c340105481a.png)

**Comment by daiyi** [comment]
Definitely not. This permission dialog seems to have been added after I last worked on the extension over a year ago, previously there wasn't even tiers of permissions. I'll look into this, thanks for bringing it up!

**Comment by MasterOfTheTiger** [comment]
I have been looking into this issue, and I am trying to find an alternative permission that will work.

**Comment by MasterOfTheTiger** [comment]
For some reason when I try to replace "<all_urls>" with "activeTab" (which theoretically should work), the newtab page never redirects.
